// <auto-generated />
using Hotel_Booking_System.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_Booking_System.Migrations.HR
{
    [DbContext(typeof(HRContext))]
    [Migration("20230528094710_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_Booking_System.Model.Hotel", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HId"));

                    b.Property<string>("HContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HPrice")
                        .HasColumnType("int");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("HId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Hotel_Booking_System.Model.Room", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<int>("HId")
                        .HasColumnType("int");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<bool>("RAvailability")
                        .HasColumnType("bit");

                    b.Property<int>("RCapacity")
                        .HasColumnType("int");

                    b.Property<int>("RPrice")
                        .HasColumnType("int");

                    b.Property<string>("RView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RId");

                    b.HasIndex("HId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel_Booking_System.Model.Room", b =>
                {
                    b.HasOne("Hotel_Booking_System.Model.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_Booking_System.Model.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
